### ISSUE TITLE
Question about metrics

### ISSUE THREAD

**Issue by sdulyq** [dc3ea9f/vico_challenge_baseline#1]
Hello, your work is really intriguing! I am trying your released code but maybe there are a little bugs.
1. There seems to be a problem with the code to calculate the Fid. The calculated value is very large, and there seems to be no average.
2. Could you release a convenient api to compute 3dmm parameters loss? A unified calculation could be fairer.

**Comment by sdulyq** [comment]
And when I run _compute_lipsync.py_, there is an error goes like this: **UnboundLocalError: local variable 'offset' referenced before assignment**

**Comment by dc3ea9f** [comment]
1. What's the FID value you calculated?
2. We will consider the api as appropriate. Shortly, the loss is calculate by this formula:
![\frac{1}{ND}\sum_{i=1}^N |\phi(x) - \phi(x')|](https://latex.codecogs.com/svg.image?\frac{1}{ND}\sum_{i=1}^N&space;|\phi(x)&space;-&space;\phi(x')|), where $N$ is #images, $x$ and $x'$ is the ground-truth and prediction images, $\phi$ maps the image to 3dmm parameters (such as `exp` etc.), $D$ is the dim of mapped feature. For head motion evaluation, `angle` and `trans` is regard as one feature.

**Comment by sdulyq** [comment]
Thank you for your timely reply. My calculated FID value is 914844765379.4113.  The folder I entered has 325 videos, I'm not sure if this is right.

**Comment by dc3ea9f** [comment]
amazing, I would try to reproduce this bug by running the script in Train Set only and try to fix this issue.

**Comment by dc3ea9f** [comment]
haven't found found any bug in FID calculation, please check your generated videos.
