### ISSUE TITLE
How to withdraw current result?

### ISSUE THREAD

**Issue by EvanJ99** [dc3ea9f/vico_challenge_baseline#10]
We apologize for our carelessness in reading the rules. We have just found that our method involves some pretrained feature extractor in the driver part, which is not allowed in the competition.

I wonder what should I do to withdraw our current result? It seems that withdraw is not supported on the competition website now. Can you help me withdraw our team's previous submissions?

**Comment by dc3ea9f** [comment]
What's your teamname please? I would help you withdraw your submissions in backend.

**Comment by EvanJ99** [comment]
**Teamname: DuiDuiDui.**

Thanks!

**Comment by dc3ea9f** [comment]
Finished.

Thanks for your honest and the support for the competition.

**Comment by EvanJ99** [comment]
Thank you. Best wishes for you.
