### ISSUE TITLE
vico.solutions 网站访问问题

### ISSUE THREAD

**Issue by P2Oileen** [dc3ea9f/vico_challenge_baseline#11]
~~如标题~~
我在过去的几分钟内尝试刷新界面，但不能成功访问；使用其他网络环境，依然无法访问，或加载极慢。
麻烦主办方排查原因，非常感谢
PS：如非网络波动问题，或许请警惕类似DDOS攻击或来自于同一ip的异常访问。这是完全可能的，鉴于一部分参赛者可能只会将最新结果短暂地挂在leaderboard上，而另一部分人会期望使用脚本不断访问vico.solutions网站以获得这些信息。

---

~~另，我们发现，在为数不多的几次成功尝试中，leaderboard均无法正常展示。~~
在最新的尝试中，我们发现vico.solutions和leaderboard可以成功访问，但速度依然很慢，且之后的几次尝试都失败了，因此我们认为该问题仍然存在。
希望能够继续排查原因，对于给主办方带来的任何不便，向您表示歉意

**Comment by P2Oileen** [comment]
在过去的几个小时内，我们做了一些尝试：使用魔法上网，虽然访问速度很慢（我确信这并非魔法上网工具的特点），且数次访问只有一次可以成功加载页面。但是，在成功加载页面后，提交功能等不受影响。
这对于比赛的影响可能是微弱的，因此我将关闭这个issue，这是一个优化的可选项，而非必须；但如果主办方有额外精力，依然希望vico challenge可以提供如以往一般的参赛体验。再次感谢您的回复

**Comment by P2Oileen** [comment]
今日我们几乎彻底无法访问vico.solutions。我们已将情况通过邮件报告mohan zhou先生。由于提交截止时间临近，我们希望可以得到尽快的回复，以防zhou先生没有收到，所以重新开启了这个issue，并期望主办方可以尽快提供一个新的提交方式。（例如，通过邮件提交文件link等）
提前感谢主办方的理解和帮助。

**Comment by dc3ea9f** [comment]
刚刚通过手机端和PC端进行了测试，通过香港、台湾、美国、日本等代理均能正常访问，直连时而可以访问时而不能访问，您看看这些信息对你是否有帮助呢？

**Comment by P2Oileen** [comment]
可能是我们的魔法上网工具太差了... : (

**Comment by dc3ea9f** [comment]
啊.....好吧，我们通过邮件沟通吧
