### ISSUE TITLE
求确认 “brief description" 接收情况

### ISSUE THREAD

**Issue by hzwer** [dc3ea9f/vico_challenge_baseline#13]
我们发现近期邮箱系统也有被墙的情况，因此我们用两个邮箱投递了我们的方法介绍，队伍名 Megvii_goodjuice；希望能在 DDL 前确认一下邮件接收情况

**Comment by dc3ea9f** [comment]
已收到。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: hzwer ***@***.***>
Sent: Monday, June 6, 2022 5:28:32 PM
To: dc3ea9f/vico_challenge_baseline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dc3ea9f/vico_challenge_baseline] 求确认 “brief description" 接收情况 (Issue #13)


我们发现近期邮箱系统也有被墙的情况，因此我们用两个邮箱投递了我们的方法介绍，队伍名 Megvii_goodjuice；希望能在 DDL 前确认一下邮件接收情况

―
