### ISSUE TITLE
How to generate a synthetic video by an audio and an image?

### ISSUE THREAD

**Issue by Minghy** [dc3ea9f/vico_challenge_baseline#14]
Hi, thanks for your working.
But I didn't see how to generate a synthetic video by an audio and an image, how to do it plz.

**Comment by dc3ea9f** [comment]
You can use the [inference](https://github.com/dc3ea9f/vico_challenge_baseline#talking-head-generation) code to get target 3DMMs and then use the [PIRender](https://github.com/dc3ea9f/vico_challenge_baseline#talking-head) to convert 3DMMs to video.

**Comment by Minghy** [comment]
> You can use the [inference](https://github.com/dc3ea9f/vico_challenge_baseline#talking-head-generation) code to get target 3DMMs and then use the [PIRender](https://github.com/dc3ea9f/vico_challenge_baseline#talking-head) to convert 3DMMs to video.
Thank you for response.
I got 3DMMs by python eval.py \
                            --batch_size 4 \
                            --output_path saved/baseline_speaker_E500 \
                            --resume saved/baseline_speaker/checkpoints/Epoch_500.bin \
                            --task speaker

But in #prepare vox lmdb# step, 
I ran python scripts/prepare_vox_lmdb.py \
        --path ../../data/listening_head/videos/ \
        --coeff_3dmm_path ../vico/saved/baseline_speaker_E500/recon_coeffs/ \
        --out ../vico/saved/baseline_speaker_E500/vox_lmdb/

Do I just need to change the path to image path?

**Comment by dc3ea9f** [comment]
you can generate a fake video by duplicating image to len(mfcc), and use that video to create vox_lmdb for visualization. For more details, please refer to [PIRender](https://github.com/RenYurui/PIRender).

**Comment by Minghy** [comment]
> you can generate a fake video by duplicating image to len(mfcc), and use that video to create vox_lmdb for visualization. For more details, please refer to [PIRender](https://github.com/RenYurui/PIRender).

I got it. Thank you!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by yogeshchandrasekharuni** [comment]
Hey @Minghy, assuming you already worked on this issue, can you please provide a notebook/script with inference? Thank you!

**Comment by yogeshchandrasekharuni** [comment]
> you can generate a fake video by duplicating image to len(mfcc), and use that video to create vox_lmdb for visualization. For more details, please refer to [PIRender](https://github.com/RenYurui/PIRender).

Can you please elaborate what you mean by duplicating an input image to len(mfcc)? If I have a portrait image of the person that is to speak the utterance, what can I do?
