### ISSUE TITLE
Expression & Head Motion

### ISSUE THREAD

**Issue by yangdaowu** [dc3ea9f/vico_challenge_baseline#15]
Hello, I'd like to ask how ExpFD, AngelFD and TransFD can be obtained. Thank you for your answer

**Comment by dc3ea9f** [comment]
Re-extract angle, expression and transformation parameter for synthesized videos and then compute L1 distance between the extracted and ground-truth.

================

Mohan Zhou
Ph.D. Student, Harbin Institute of Technology
https://www.mhzhou.com/
________________________________
From: yangdaowu ***@***.***>
Sent: Wednesday, October 19, 2022 6:50:15 PM
To: dc3ea9f/vico_challenge_baseline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dc3ea9f/vico_challenge_baseline] Expression & Head Motion (Issue #15)


Hello, I'd like to ask how ExpFD, AngelFD and TransFD can be obtained. Thank you for your answer

**Comment by yangdaowu** [comment]
Do you want to run Step 5 to process the composite video first
![image](https://user-images.githubusercontent.com/64669901/196673146-9df364e9-43fe-49e4-bdcd-afd1f1e7cc97.png)

**Comment by dc3ea9f** [comment]
Yes, we use that to extract 3dmm coefficients and then compute the L1 distance.
________________________________

**Comment by yangdaowu** [comment]
That is, can you calculate the L1 distance for the mat file under the recons files of both? Can you send the code to calculate the L1 distance? Thank you！
![image](https://user-images.githubusercontent.com/64669901/196674311-3a8c1d7e-75b4-49a6-b3a6-2851fb257263.png)

**Comment by dc3ea9f** [comment]
Yes, the mat file format can be revealed from https://github.com/dc3ea9f/vico_challenge_baseline/blob/f224c65f0b1b7fcfcf8f422912d44be42468c92b/preprocess/rearrange_recon_coeffs.py#L10, you can just get those coefficients, compute l1 for each frame of the dataset, and then average. I would share the code snippet later.

================

Mohan Zhou
Ph.D. Student, Harbin Institute of Technology
https://www.mhzhou.com/
________________________________

**Comment by yangdaowu** [comment]
Okay, thank you very much for your answer. Thank you very much.

**Comment by dc3ea9f** [comment]
```python
import pandas as pd
import argparse
from tqdm import tqdm
import numpy as np
from scipy.io import loadmat
from collections import defaultdict

def load_feats(fn):
    mat = loadmat(fn)
    coeff_3dmm = mat['coeff']
    _id = coeff_3dmm[:, :80]
    _exp = coeff_3dmm[:, 80:144]
    _tex = coeff_3dmm[:, 144:224]
    _angle = coeff_3dmm[:, 224:227]
    _gamma = coeff_3dmm[:, 227:254]
    _trans = coeff_3dmm[:, 254:257]
    _crop = mat['transform_params'][:, -3:]
    result = {
        'id': _id,
        'exp': _exp,
        'tex': _tex,
        'angle': _angle,
        'gamma': _gamma,
        'trans': _trans,
        'crop': _crop,
    }
    return result

def align_with_gt(pd_feats, gt_feats):
    result = {}
    for key in pd_feats.keys():
        pd_value = pd_feats[key]
        gt_value = gt_feats[key]
        if len(pd_value) > len(gt_value):
            pd_value = pd_value[:len(gt_value)]
        elif len(pd_value) < len(gt_value):
            pd_value = np.concatenate((pd_value, pd_value[-1][None, ...].repeat(len(gt_value) - len(pd_value), axis=0)), axis=0)
        else:
            pass
        result[key] = pd_value
    return result
        

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--gt_video_folder', type=str, required=True)
    parser.add_argument('--pd_video_folder', type=str, required=True)
    parser.add_argument('--task', type=str, required=True, choices=['speaker', 'listener'])
    parser.add_argument('--anno_file', type=str, required=True)
    args = parser.parse_args()

    df = pd.read_csv(args.anno_file, dtype=str)
    result = defaultdict(list)
    for row_idx, row in tqdm(df.iterrows(), total=len(df)):
        gt_feats_fn = f'{args.gt_video_folder}/recons/test/{row[args.task]}.mat'
        pd_feats_fn = f'{args.pd_video_folder}/recons/test/{row[args.task]}.mat'

        gt_feats = load_feats(gt_feats_fn)
        pd_feats = load_feats(pd_feats_fn)
        pd_feats = align_with_gt(pd_feats, gt_feats)
        
        for key in pd_feats.keys():
            distance = np.abs(gt_feats[key] - pd_feats[key])
            result[key].append(distance)

    for key, value in result.items():
        if key in ['angle', 'exp', 'trans']:
            print(key, np.mean(np.concatenate(value, axis=0)))
```

**Comment by yangdaowu** [comment]
Thank you very much.
