### ISSUE TITLE
About "video_feats_mean_std.bin" and "audio_feats_mean_std.bin"

### ISSUE THREAD

**Issue by Minghy** [dc3ea9f/vico_challenge_baseline#16]
Hello, thanks for your working.

I want to generate my our synthetic video according to my image and audio, should I generate a new "video_feats_mean_std.bin" and "audio_feats_mean_std.bin" according to my image and audio or using  "video_feats_mean_std.bin" and "audio_feats_mean_std.bin" that generated by training data?

**Comment by dc3ea9f** [comment]
Yes.
