### ISSUE TITLE
ModuleNotFoundError: No module named 'box'

### ISSUE THREAD

**Issue by azuredsky** [dc3ea9f/vico_challenge_baseline#18]
when I run train.py it shows that in vico/data.py ModuleNotFoundError: No module named 'box'

from box import Box
ModuleNotFoundError: No module named 'box'

**Comment by dc3ea9f** [comment]
run `python -m pip install python-box`
python-box: https://pypi.org/project/python-box/

**Comment by azuredsky** [comment]
thank you
