### ISSUE TITLE
Ranking results

### ISSUE THREAD

**Issue by yangdaowu** [dc3ea9f/vico_challenge_baseline#19]
Hello, we can't find the result of the challenge leaderboard by opening the website now. Is it closed. How to get the results of the leaderboard. Tanks！

**Comment by dc3ea9f** [comment]
You can access the public leaderboard of our challenge @ACM MM 2022 is https://vico.solutions/leaderboard/2022.
For challenge in ACM MM 2023, the registration, submission, and leaderboard will be available soon. While you can fill in [this form](https://forms.gle/vrPirQuVFPd716Kd9) to subscribe to changes of our challenge.

**Comment by yangdaowu** [comment]
Thank you very much for your answer！Thanks！
