### ISSUE TITLE
Video Pose Driven Condition

### ISSUE THREAD

**Issue by FeiiYin** [dc3ea9f/vico_challenge_baseline#2]
From the provided dataset, the input is the first frame and the audio.
So the pose of synthesis results is purely from audio conditions?

**Comment by dc3ea9f** [comment]
For talking head generation, yes. And in test set, besides the first frame and the audio, we also provide a ref image.

For listening head generation, besides these, the speaker’s frames are also provided.

**Comment by FeiiYin** [comment]
Thanks
