### ISSUE TITLE
About external data

### ISSUE THREAD

**Issue by P2Oileen** [dc3ea9f/vico_challenge_baseline#4]
> Except for the driver part, all other parts (e.g. render) can use additional data, but teams need to declare the pretrained model or additional data used when submission. For example, the use of a Talking Head Generation data is not allowed, but the use of pretrained data / model to adjust the render is allowed.

I saw this on the [competition website](https://vico-challenge.github.io/#:~:text=in%20talking_head.zip.-,**Note%3A,-Except%20for%20the) but didn't understand the meaning of “driver part” even with the example. I also tried to search "driver" in the code and paper but found nothing. Could you please be more specific？ 
Thank you.

**Comment by dc3ea9f** [comment]
The "driver" part means the mapping from audio to speaker's expression / pose, this corresponding to G_m (Equation 2) in our paper, and the other parts (e.g. render) is G_v.

**Comment by P2Oileen** [comment]
Thanks for your reply. One additional doubt: let's say I have a standard imagenet-pretrained model, which is not trained on any "driver" related data. So can I use it to extract the features of V_t^s?
