### ISSUE TITLE
Time zone issue

### ISSUE THREAD

**Issue by P2Oileen** [dc3ea9f/vico_challenge_baseline#5]
Since the results can only be submitted once a day, I hope to know the specific rules for the submission time. For example, can it be submitted once every 24 hours or once per date? The difference is that the former requires a strict 24-hour interval between submissions, while the latter does not.
 If the latter, what is the timezone for the date?
[Important dates](https://vico-challenge.github.io/#:~:text=this%20github%20repo.-,Important%20Dates,-Important%20Dates%20and) on the website uses the standard time zone AoE. However, the submission time logged on [submit website](https://vico.solutions/) does not seem the same. The inconsistency is the reason for my confusion, and I hope it can be answered.
Thank you very much.

**Comment by dc3ea9f** [comment]
For submission time limits, we use the server time (UTC-0) rather than AoE (UTC-12). It can be submitted once per date.

**Comment by P2Oileen** [comment]
Thank you! It helps :)
