### ISSUE TITLE
在生成test集中某段视频的时候，可否使用其他视频的第一帧呢？

### ISSUE THREAD

**Issue by P2Oileen** [dc3ea9f/vico_challenge_baseline#6]
考虑到存在一个人物id可能对应多段视频uuid的情况

**Comment by wyvernbai** [comment]
> 考虑到存在一个人物id可能对应多段视频uuid的情况

原则上test set中得每一个样本都是被看成独立样本得，所以应该是使用我们给定得GT test video中的第一帧结合ref image进行视频生成得。此外，使用其他视频的第一帧会导致初始状态跟GT video不同，结果差异可能会较大。
