### ISSUE TITLE
在提交截止后，是否还有时间可以选择某一个模型作为最终结果呢？

### ISSUE THREAD

**Issue by P2Oileen** [dc3ea9f/vico_challenge_baseline#7]
由于提交之后需要时间进行评测，在提交截止时间前进行提交，可能会导致截止时评测结果还未出。
因此，提交截止后的情况会是以下哪一种？
1. 有时间可供选择一个已提交的模型上榜
2. 一切操作在截止时停止
3. 其他（如果是这样，还烦请您提供一些详细解释，非常感谢）

**Comment by dc3ea9f** [comment]
AoE time June 3 11:59pm，网站会拒接所有提交请求，我们会对已提交的结果进行评测；
AoE time June 4 11:59pm，所有评测结果都会被返回给用户，用户可以自由选择模型上榜；
AoE time June 5 11:59pm，网站关闭用户模型选择通道，fix leaderboard；
