### ISSUE TITLE
提交评测问题

### ISSUE THREAD

**Issue by halo2718** [dc3ea9f/vico_challenge_baseline#9]
我们队伍在6.2 11:33 p.m. (UTC+8) 提交了一版结果，队名是TalkingHead，现在已经过去了将近11个小时了，但是还没有评测结果的反馈。请问一下这是我们的提交格式有误，还是视频格式有误？或者是现在服务器正在评测吗？

谢谢！

**Comment by dc3ea9f** [comment]
Please check your email to fix this issue.

**Comment by EvanJ99** [comment]
收到，谢谢！

**Comment by halo2718** [comment]
收到，谢谢！
